### ISSUE TITLE
每次发布新内容，用户都要手动点击才能更新cache......能不能访问网页就自动更新的？

### ISSUE THREAD

**Issue by wtnyzhsq** [DaiwenZh5/hexo-service-worker-tooltip#1]

**Comment by daiwenzh5** [comment]
呃，正常来说，打开页面就会缓存最新的内容了，不需要点击，service-worker 会在后台的另一个线程对比当前文件的版本号，当版本不一致时就会更新，这个版本号是 hexo 打包时写入的 hash、时间戳等唯一标识
![image](https://user-images.githubusercontent.com/29970117/109742686-7aff4900-7c0a-11eb-9a3e-fecbf469c866.png)
